default: &default
  adapter: postgresql
  encoding: unicode
  username: postgres
  password: 123456
  host: localhost
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: recruitment_api_development

test:
  <<: *default
  database: recruitment_api_test

production:
  <<: *default
  database: recruitment_api_production
  username: recruitment_api
  password: <%= ENV['RECRUITMENT_API_DATABASE_PASSWORD'] %>
